### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by darylknight** [pixelandtonic/StoreHours#2]
Hi guys,
Any chance of some very basic documentation being added to the readme for this plugin please? There's nothing here about how to output data.

**Comment by thomasthesecond** [comment]
I was able to output the data using this code:

```twig
{% set days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] %}

{% for hour in entry.storeHours %}
    <div>{{ days[loop.index0] }}: {{ hour.open|date('h:i a') }} - {{ hour.close|date('h:i a') }}</div>
{% endfor %}
```

You need to set a days array because the plugin does not give them to you. Run `{{ dump(entry.storeHours) }}` in your template and you'll see what I mean.

But unfortunately, due to the [time zone bug](https://github.com/pixelandtonic/StoreHours/issues/3), this plugin is unusable.

**Comment by rylanb** [comment]
https://github.com/pixelandtonic/StoreHours/pulls added documentation. It appears maybe a TimeZone fix was committed?
